import { presetUno, presetAttributify, presetIcons } from "unocss";
import Unocss from "unocss/vite";

const colors = ["primary", "warning", "danger", "success", "waiting"];
const safelist = [
  "bg-primary",
  "bg-danger",
  "bg-warning",
  "bg-default",
  "bg-success",
  "text-primary",
  "text-danger",
  "text-warning",
  "text-default",
  "text-success",
  "border-primary",
  "border-danger",
  "border-warning",
  "border-default",
  "border-success",
  "hover:bg-hover-primary",
  "hover:bg-hover-danger",
  "hover:bg-hover-warning",
  "hover:bg-hover-success",
  "hover:border-hover-primary",
  "hover:border-hover-danger",
  "hover:border-hover-warning",
  "hover:border-hover-success",
  "hover:text-hover-primary",
  "hover:text-hover-danger",
  "hover:text-hover-warning",
  "hover:text-hover-success",
  ...colors.map((v) => `border-${v}-400`),
  ...colors.map((v) => `border-${v}-500`),
  ...colors.map((v) => `text-${v}-500`),
  ...colors.map((v) => `hover:text-${v}-500`),
  "text-white",
  ...Array.from({ length: 8 }, (_, i) => `px-${i + 1}`),
  ...Array.from({ length: 8 }, (_, i) => `py-${i + 1}`),
  ...["xs", "sm", "base", "lg", "xl", "2xl", "3xl"].map((v) => `text-${v}`),
  ...["rounded-full", "rounded-lg"],
  ...[
    "search",
    "edit",
    "check",
    "message",
    "star-off",
    "delete",
    "add",
    "share",
  ].map((v) => `i-ic-baseline-${v}`),
];

export default () =>
  Unocss({
    presets: [presetUno(), presetAttributify(), presetIcons()],
    safelist,
    rules: [
      ["bg-primary", { "background-color": "#6189f8" }],
      ["bg-danger", { "background-color": "#ee4847" }],
      ["bg-warning", { "background-color": "#ffd81a" }],
      ["bg-success", { "background-color": "#51c000" }],
      ["bg-default", { "background-color": "#ffffff" }],
      ["border-primary", { "border-color": "#6189f8" }],
      ["border-danger", { "border-color": "#ee4847" }],
      ["border-warning", { "border-color": "#ffd81a" }],
      ["border-success", { "border-color": "#51c000" }],
      ["border-default", { "border-color": "#ffffff" }],
      ["text-primary", { color: "#6189f8" }],
      ["text-danger", { color: "#ee4847" }],
      ["text-warning", { color: "#ffd81a" }],
      ["text-success", { color: "#51c000" }],
      ["text-default", { color: "#ffffff" }],
      ["bg-hover-primary", { "background-color": "#6b8bf3" }],
      ["bg-hover-danger", { "background-color": "#f85755" }],
      ["bg-hover-warning", { "background-color": "rgba(255, 216, 26, .8)" }],
      ["bg-hover-success", { "background-color": "rgba(81, 192, 0, .8)" }],
      ["border-hover-primary", { "border-color": "#6b8bf3" }],
      ["border-hover-danger", { "border-color": "#f85755" }],
      ["border-hover-warning", { "border-color": "rgba(255, 216, 26, .8)" }],
      ["border-hover-success", { "border-color": "rgba(81, 192, 0, .8)" }],
      ["text-hover-primary", { color: "#6b8bf3" }],
      ["text-hover-danger", { color: "#f85755" }],
      ["text-hover-warning", { color: "rgba(255, 216, 26, .8)" }],
      ["text-hover-success", { color: "rgba(81, 192, 0, .8)" }],
    ],
  });
